"""empty message

Revision ID: 043853e356ff
Revises: 06f5c8237ddb
Create Date: 2022-05-26 15:47:54.220262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043853e356ff'
down_revision = '06f5c8237ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')

    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
